/** @type {import("prettier").Config} */
const config = {
	printWidth: 80,
	useTabs: true,
	tabWidth: 2,
	singleQuote: true,
	bracketSpacing: true,
	trailingComma: 'all',
	semi: true,
	plugins: ['@ianvs/prettier-plugin-sort-imports'],
	importOrder: [
		'^react',
		'^next',
		'<THIRD_PARTY_MODULES>',
		'',
		'^@modules/(.*)$',
		'^@icons/(.*)$',
		'',
		'^@hooks/(.*)$',
		'^@utils/(.*)$',
		'^@styles/(.*)$',
		'',
		'^@public/(.*)$',
		'^@modules/(.*)/assets(.*)$',
		'',
		'^@t-types/(.*)$',
		'<TYPES>',
		'<TYPES>^[.]',
		'',
		'^./assets/(.*)$',
		'',
		'^[./]',
		'',
	],
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderTypeScriptVersion: '5.0.0',
};

export default config;
