module.exports = {
	sortingMethod: 'lineLength',
	plugins: ['./node_modules/prettier-plugin-sort-imports/dist/index.js'],
	printWidth: 80,
	useTabs: true,
	tabWidth: 1,
	singleQuote: true,
	bracketSpacing: true,
	trailingComma: 'all',
	semi: true,
	importOrder: [
		'^react',
		'^next',
		'<THIRD_PARTY_MODULES>',
		'',
		'^@modules/(.*)$',
		'^@icons/(.*)$',
		'',
		'^@hooks/(.*)$',
		'^@utils/(.*)$',
		'^@styles/(.*)$',
		'',
		'^@public/(.*)$',
		'^@modules/(.*)/assets(.*)$',
		'',
		'^@t-types/(.*)$',
		'<TYPES>',
		'<TYPES>^[.]',
		'',
		'^./assets/(.*)$',
		'',
		'^[./]',
		'',
	],
	importOrderBuiltinModulesToTop: true,
	importOrderCaseInsensitive: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderMergeDuplicateImports: true,
	// importOrderCombineTypeAndValueImports: true,
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
};
